@startuml

title Rich Schema Credential Prerequisites
participant VDR as L
actor Issuer as I
actor Holder as H

I -> L: check for existing cred def

alt if no cred def
I->L: check for existing mapping

alt if no mapping
I->L: check for existing schemas

alt if no schemas
I->L: anchor context(s)
I->L: anchor schema(s)
end

I->L: anchor mapping

end

I->L: anchor cred def

end

I->H: issue credential

@enduml